### PR TITLE
[suggestion] cleaner build interface enabling wheels

### PR DESCRIPTION
**Pull request by cdiener**
Hi,

I have some collaborators that wanted cobrame on Windows. So here some suggestions to make that possible. This PR extends `setup.py` in order to allow easier builds. It compiles soplex along with the extension which also gets rid of the missing symbols in the soplex dynamic libs (also the only way I found that works on windows due to the same problem).

Major change is that the repo now includes the patched source. This should not change the licensing terms though since the soplex license enforces the same requirements for compilation as for distribution (academics only etc.). Those terms would have to be mentioned on the README. The soplex license itself is included in tgz. 

For Linux/Mac it is now sufficient to install GMP and run 

```bash
pip install .
```
Linux and Mac wheel builds should become straight forward with that.

On windows you will need MPIR (GMP replacement that compiles with Visual Studio). However, the PR also includes an appveyor setup that will create [64bit Windows wheels](https://ci.appveyor.com/project/cdiener/soplex-cython) for distribution. Only for 3.5+ though due to the required C++0x/11 features for soplex that are not supported by lower Python versions.

Hope it helps...

### CODE REVIEW

**Comment by coltonlloyd** [comment]
Hello,

This is really great. Thank you! 

I'll merge it into a new branch for now while I try it out and update the README.

**Comment by cdiener** [comment]
Sure sounds good. We could also port the cobrapy travis setup (uses multibuild) so you would have automated wheel building for Linux and Mac as well. Depends on your plans though.

**Comment by coltonlloyd** [comment]
Thank you again for this PR. This installation procedure has needed troubleshooting quite a bit so I appreciate suggestions for simplifying it. 

I have one concern with providing the soplex source code though (release 3.0.1 corrected the bug so the patch will no longer be needed). The ZIB License terms states in section 3c that in order to distribute the program:

"You must keep track of access to the Program (e.g., similar to the registration procedure at ZIB). " 

 Do you have any suggestions for how to comply with that section of the License?

**Comment by cdiener** [comment]
Wow that license is pretty horrible. I don't think this part has any legal validity given that is does never specify what "keep track of" means. Also this may apply to compiled code as well which would prohibit wheels. If we could at least distribute the compile code I think we could fix it by using an encrypted version of the source on the CI.

**Pull request merged**
